// app/layout.js or app/layout.tsx (NO 'use client')
import "./globals.css";
import { outfit, ovo } from "./fonts";

export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}>
        {children}
      </body>
    </html>
  );
}
